# Generated by Django 6.0.4 on 2026-04-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fifa_code', models.CharField(blank=True, max_length=10)),
                ('confederation', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_matches', models.IntegerField(default=104)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to='api.team')),
                ('runner_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_placements', to='api.team')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place_placements', to='api.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=10)),
                ('fifa_match_number', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=10)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('score_detail', models.TextField(blank=True)),
                ('prob_home_win', models.FloatField(blank=True, null=True)),
                ('prob_draw', models.FloatField(blank=True, null=True)),
                ('prob_away_win', models.FloatField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.simulationrun')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='api.team')),
            ],
            options={
                'ordering': ['match_id'],
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_diff', models.IntegerField()),
                ('points', models.IntegerField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='api.simulationrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_standings', to='api.team')),
            ],
            options={
                'ordering': ['group', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_reached', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_diff', models.IntegerField()),
                ('group', models.CharField(max_length=10)),
                ('group_position', models.IntegerField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='api.simulationrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to='api.team')),
            ],
            options={
                'ordering': ['-stage_reached', '-wins', '-goal_diff'],
            },
        ),
    ]
