# Generated by Django 6.0.4 on 2026-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='simulation_type',
            field=models.CharField(choices=[('modern', 'Modern (Recency Weighted)'), ('all_time', 'All-Time (Equal Weights)')], db_index=True, default='modern', help_text='Type of simulation: modern (recency weighted) or all_time (equal weights for all years)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['simulation_type', '-created_at'], name='api_simulat_simulat_2ccdd2_idx'),
        ),
    ]
